
trigger:
  branches:
    include:
      - master

pr:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
     #goals: 'clean install'
      goals: 'package'

  - task: CopyFiles@2
    inputs:
      targetFolder: '$(Build.ArtifactStagingDirectory)' 

 # - script: 'ls $(Build.SourcesDirectory)/target'
 #   displayName: 'List files in target directory'

  - task: PublishBuildArtifacts@1
    inputs:
      #PathtoPublish: '$(Build.SourcesDirectory)/target/*.jar'
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'java-app'
      publishLocation: 'Container'

  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      artifactName: 'java-app'
      downloadPath: '$(System.ArtifactsDirectory)'

  - task: AzureWebApp@1
    displayName: 'Deploy to Azure Web App'
    inputs:
      azureSubscription: 'my-git-connection'  # Replace with the name of your Azure Resource Manager service connection
      appType: 'webApp'
      appName: 'sampleapp-githubactions'
      package: '$(System.ArtifactsDirectory)/java-app/**/*.jar'
      deploymentMethod: 'auto'
      ResourceGroupName: 'GitHubPOC'

#  - task: AzureCLI@2
#    inputs:
#     scriptType: 'bash'
#      scriptLocation: 'inlineScript'
#      inlineScript: |
#        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

#  - task: AzureCLI@2
#    inputs:
#      #azureSubscription: 'demo-con-name'
#      scriptType: 'bash'
#      scriptLocation: 'inlineScript'
#      inlineScript: |
#        az webapp up --name sampleapp-githubactions --resource-group demosv --sku F1 --location EastUS --verbose